[package]
name = "todo_cli_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
structopt = "0.3"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
colored = "2.0"
clap = { version = "4.0", features = ["derive"] }